services:
  # Databases
  auth-db:
    image: postgres:16-alpine
    container_name: auth-db
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
    volumes:
      - auth-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  course-db:
    image: postgres:16-alpine
    container_name: course-db
    environment:
      POSTGRES_DB: course_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
    volumes:
      - course-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  enrollment-db:
    image: postgres:16-alpine
    container_name: enrollment-db
    environment:
      POSTGRES_DB: enrollment_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
    volumes:
      - enrollment-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Services
  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://auth-db:5432/auth_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456789
    depends_on:
      auth-db:
        condition: service_healthy

  course-service:
    build: ./course
    container_name: course-service
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://course-db:5432/course_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456789
    depends_on:
      course-db:
        condition: service_healthy

  enrollment-service:
    build: ./enrollment_service
    container_name: enrollment-service
    ports:
      - "8084:8084"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://enrollment-db:5432/enrollment_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456789
    depends_on:
      enrollment-db:
        condition: service_healthy

  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "8080:8080"
    environment:
      AUTH_SERVICE_URL: http://auth-service:8082
      COURSE_SERVICE_URL: http://course-service:8083
      ENROLLMENT_SERVICE_URL: http://enrollment-service:8084
    depends_on:
      - auth-service
      - course-service
      - enrollment-service

volumes:
  auth-data:
  course-data:
  enrollment-data: