server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        # Auth service — no JWT needed
        - id: auth-service
          uri: http://localhost:8082
          predicates:
            - Path=/auth/**

        # Course service
        - id: course-service
          uri: http://localhost:8083
          predicates:
            - Path=/courses/**
          filters:
            - AuthFilter

        # Enrollment service
        - id: enrollment-service
          uri: http://localhost:8084
          predicates:
            - Path=/inscriptions/**
          filters:
            - AuthFilter

app:
  jwt:
    secret: your-super-secret-key-that-is-at-least-32-characters