server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-service.railway.internal:8082
          predicates:
            - Path=/auth/**

        - id: course-service
          uri: http://course-service.railway.internal:8083
          predicates:
            - Path=/courses/**

        - id: enrollment-service
          uri: http://enrollment-service.railway.internal:8084
          predicates:
            - Path=/inscriptions/**

app:
  jwt:
    secret: your-super-secret-key-that-is-at-least-32-characters